apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-33id
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-33id
    app.kubernetes.io/part-of: integ-app-kmei
  name: hacbs-test-project-33id
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-33id
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-33id
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/integration1-ctih-tenant/integ-app-kmei/hacbs-test-project-33id@sha256:28f90c3e36f6e3e31d1ff5fe1bbdc036c9915256c57180c2c6033793cfa5d7b2
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 25Mi
status: {}
